module Hansa
  CITY_NAMES = {
    a: ['Atlanta', 'Athens'],
    b: ['Birmingham', 'Bombay'],
    c: ['Chicago', 'Charleston'],
    d: ['Denver', 'Dusseldorf'],
    e: ['El Paso', 'Eindhoven'],
    f: ['Fargo', 'Frankfurt'],
    g: ['Grand Rapids', 'Glasgow'],
    h: ['Helena', 'Hamburg'],
    i: ['Indianapolis', 'Istanbul'],
    j: ['Jacksonville', 'Jersey'],
    k: ['Kansas City', 'Krakow'],
    l: ['Louisville', 'London'],
    m: ['Milwaukee', 'Manchester'],
    n: ['New York City', 'Nairobi'],
    o: ['Olympia', 'Oslo'],
    p: ['Philadelphia', 'Paris'],
    q: ['Quincy', 'Quito'],
    r: ['Redmond', 'Rome'],
    s: ['Savannah', 'Seville'],
    t: ['Tucson', 'Torino'],
    u: ['Urbana', 'Uvalde'],
    v: ['Virginia Beach', 'Vienna'],
    w: ['Washington D.C.', 'Wuhan'],
    x: ['Xenia', "Xi'ian"],
    y: ['Yonkers', 'Yokohama'],
    z: ['Zion', 'Zhengzhou'],
  }
end
